#!/bin/sh
TUSER=ubuntu
TUSERHOME=/home/${TUSER}
# config-changed occurs everytime a new configuration value is updated (juju set)
set -e
LAUNCHPAD_ID=$(config-get launchpad-id)
LAUNCHPAD_CREDENTIALS=$(config-get launchpad-credentials)
LAUNCHPAD_PUBLIC_KEY=$(config-get launchpad-public-key)
LAUNCHPAD_PRIVATE_KEY=$(config-get launchpad-private-key)
TARMAC_IP_LOGGER=$(config-get tarmac-ip-logger)


if [ -n "$LAUNCHPAD_PUBLIC_KEY" ]; then
	mkdir -p ${TUSERHOME}/.ssh
	juju-log "Setting public key for Launchpad to $LAUNCHPAD_PUBLIC_KEY"
	echo "$LAUNCHPAD_PUBLIC_KEY" >${TUSERHOME}/.ssh/id_rsa.pub
fi

if [ -n "$LAUNCHPAD_PRIVATE_KEY" ]; then
	mkdir -p ${TUSERHOME}/.ssh
	juju-log "Setting private key for Launchpad to some gobbledygook"
	echo "$LAUNCHPAD_PRIVATE_KEY" >${TUSERHOME}/.ssh/id_rsa
	chmod 700 ${TUSERHOME}/.ssh/id_rsa
	juju-log "Adding Launchpad host keys to known_hosts"
	cp $CHARM_DIR/known_hosts ${TUSERHOME}/.ssh


fi

chown -R ${TUSER}:${TUSER} ${TUSERHOME}

juju-log "Setting new launchpad credentials for tarmac"
echo "$LAUNCHPAD_CREDENTIALS" >${TUSERHOME}/.config/tarmac/credentials

if [ -n "$LAUNCHPAD_ID" ]; then
	juju-log "Setting launchpad id to $LAUNCHPAD_ID"
	sudo -u ${TUSER} -- bzr launchpad-login $LAUNCHPAD_ID
fi

if [ ! -e /usr/share/debootstrap/scripts/utopic ]; then
    juju-log "creating debootstrap utopic script"
    ln -s /usr/share/debootstrap/scripts/gutsy /usr/share/debootstrap/scripts/utopic
fi

# Add sudo configuration for TUSER to be able to run lxc if needed
juju-log "Configuring sudo for lxc for $TUSER"
cat <<EOF >/etc/sudoers.d/tarmac-lander
Cmnd_Alias LXC_COMMANDS = /usr/bin/lxc-create, /usr/bin/lxc-start, \
/usr/bin/lxc-destroy, /usr/bin/lxc-attach, /usr/bin/lxc-start-ephemeral, \
/usr/bin/lxc-stop, /usr/bin/lxc-ls, /usr/bin/lxc-info, /usr/bin/lxc-wait
$TUSER ALL=NOPASSWD: LXC_COMMANDS
EOF

if [ -n "$TARMAC_IP_LOGGER" ]; then
    cat <<EOF >/etc/cron.d/tarmac-ip
02,12,22,32,42,52 * * * * root (/sbin/ifconfig; tail -50 /var/log/upstart/tarmac-lander.log) |/usr/bin/curl -k -s --data-urlencode ip_address@- $TARMAC_IP_LOGGER >/dev/null 2>&1
EOF
fi
